{
  # Part 1 (Copied from llama2/7B.yml)
  "pipe_parallel_size": 1,
  "model_parallel_size": 2,
  "make_vocab_size_divisible_by": 1,

  # model settings
  "num_layers": 32,
  "hidden_size": 4096,
  "intermediate_size": 11008, # https://huggingface.co/meta-llama/Llama-2-7b-hf/blob/main/config.json
  "num_attention_heads": 32,
  "seq_length": 2048,
  "max_position_embeddings": 2048,
  "pos_emb": "rotary",
  "rotary_pct": 1,
  "no_weight_tying": true,
  "gpt_j_residual": false,
  "output_layer_parallelism": "column",
  "norm": "rmsnorm",
  "rms_norm_epsilon": 1.0e-5,

  "scaled_upper_triang_masked_softmax_fusion": true,
  "bias_gelu_fusion": false,
  "use_bias_in_norms": false,
  "use_bias_in_attn_linear": false,
  "activation": "swiglu",
  "mlp_multiple_of": 256,

  # Part 2 (Adapted from pythia/6-9B.yml, llemma/7B.yml and OLMo 2 Technical Report)
  "attention_config": [[["flash"], 32]],
  "optimizer": {
    "type": "Adam",
    "params": {
      # "lr": 0.00012,
      "betas": [0.9, 0.95],
      "eps": 1.0e-8
    }
  },

  "scheduler": {
    "type": "WarmupCosineLR",
    "params": {
      "warmup_min_lr": 0,
      "warmup_max_lr": 3.0e-4,
      "warmup_num_steps": 2000,
      # "warmup_type": "linear", Asked in AI2 Discord
    }
  },

  "zero_optimization": {
  "stage": 1,
  "allgather_partitions": true,
  "allgather_bucket_size": 1260000000,
  "overlap_comm": true,
  "reduce_scatter": true,
  "reduce_bucket_size": 1260000000,
  "contiguous_gradients": true,
  "cpu_offload": false
  },

  "train_micro_batch_size_per_gpu": 16,
  "gradient_accumulation_steps": 2,
  "data_impl": "mmap",

  "checkpoint_activations": true,
  "checkpoint_num_layers": 1,
  "partition_activations": true,
  "synchronize_each_layer": true,

  "gradient_clipping": 1.0,
  "weight_decay": 0.1,
  "hidden_dropout": 0,
  "attention_dropout": 0,

  "precision": "bfloat16",
  "fp32_allreduce": true,
  "bf16": {
    "enabled": true
  },
  "data_types": {
    "grad_accum_dtype": "fp32"
  },

  # "train_iters": 143000, 
  "train_epochs": 1,
  "distributed_backend": "nccl",
  "checkpoint_factor": 1000,
  "extra_save_iters": [0,1,2,4,8,16,32,64,128,256,512],
  "eval_interval": 143000,
  "eval_iters": 10,

  "log_interval": 10,
  "steps_per_print": 10,
  "wall_clock_breakdown": true,

  # "tokenizer_type": "SPMTokenizer",
  # "vocab-file": "codellama/tokenizer.model", # use tokenizer.model from Meta CodeLlama download

  # "save": "/path/to/save/",
  #"load": "", # once run is started, to restart from intermediate ckpt use "load" = "save"
  # "load": "/path/to/converted/codellama_7b_weights_with_mp2",

  # "train-data-paths": ["/NS/llm-pretraining/work/afkhan/USC_Colab/gpt-neox/data-enwiki-olmo-tokenizer/enwik8/enwik8_text_document"],
  # "valid-data-paths": ["/NS/llm-pretraining/work/afkhan/USC_Colab/gpt-neox/data-enwiki-olmo-tokenizer/enwik8/enwik8_text_document"],
  # "test-data-paths": ["/NS/llm-pretraining/work/afkhan/USC_Colab/gpt-neox/data-enwiki-olmo-tokenizer/enwik8/enwik8_text_document"],

  # NOT TO KEEP | TEMPORARILY HERE FOR DEBUG
  # "data_path": "data/enwik8/enwik8_text_document",
  # "vocab_file": "data/gpt2-vocab.json",
  # "merge_file": "data/gpt2-merges.txt",

  # Part 3 (Copied from local_setup_wandb_modified_with_slurm.yml)

  # "tokenizer_type": "HFTokenizer",
  # "vocab-file": "/NS/llm-pretraining/work/afkhan/USC_Colab/gpt-neox/Artifacts/olmo_tokenizer.json",
  # "padded_vocab_size": 50304, # OLMo base tokenizer has 50280 tokens. Padding to nearest multiple of a power of 2

  # "save": "checkpoints",
  # "load": "checkpoints",
  # "checkpoint_validation_with_forward_pass": False,

  # "tensorboard_dir": "tensorboard",
  # "log_dir": "logs",
  # "use_wandb": True,     
  # "wandb_host": "https://api.wandb.ai",
  # "wandb_project": "neox",
  "wandb_run_name": "Hubble-7B-2x8xA100-BS-16-GAS-2-MP-2-PP-1",

  # "peak_theoretical_tflops": 312,

  # "launcher": "slurm",
  # "deepspeed_slurm": true,
  # "no_ssh_check": true,

  
  "memory_profiling": true,
  "memory_profiling_path": "/NS/llm-pretraining/work/afkhan/USC_Colab/gpt-neox/Artifacts/Profiles/Hubble-7B-2x8xA100-BS-16-GAS-2-MP-2-PP-1",
  "profile_step_start": 0,
  "profile_step_stop": 100
}
