# Hubble 1.1B - Copied from TinyLlama https://github.com/Lightning-AI/litgpt/blob/a5021be4bb48e27779586b56b062a1749ecb232f/litgpt/config.py#L1809 
{
   # parallelism settings ( you will want to change these based on your cluster setup, ideally scheduling pipeline stages
   # across the node boundaries )
   "pipe_parallel_size": 1,
   "model_parallel_size": 1,
  "make_vocab_size_divisible_by": 128, # Need to set as 64 because code makes it divisible by MP*makes_vocab_size_divisible_by

   # model settings
   "num_layers": 22,
   "hidden_size": 2048,
   "num_attention_heads": 32,
   "intermediate_size": 16896,
   "seq_length": 2048,
   "max_position_embeddings": 2048,
   "pos_emb": "rotary",
   "no_weight_tying": true,
   "gpt_j_residual": false,
   "output_layer_parallelism": "column",
    "norm": "rmsnorm",
    "rms_norm_epsilon": 1.0e-5,

  #  "num_layers": 24,
  #  "hidden_size": 2048,
  #  "num_attention_heads": 16,
  #  "seq_length": 2048,
  #  "max_position_embeddings": 2048,
  #  "norm": "layernorm",
  #  "pos_emb": "rotary",
  #  "no_weight_tying": true,
  #  "gpt_j_residual": false,
  #  "output_layer_parallelism": "column",
    
   # these should provide some speedup but takes a while to build, set to true if desired
   "scaled_upper_triang_masked_softmax_fusion": false,
   "bias_gelu_fusion": false,
  #  "rope_fusion": false,
  #  "layernorm_fusion": false,
   "use_bias_in_norms": false,
   "use_bias_in_attn_linear": false,
  "activation": "swiglu",
  "mlp_multiple_of": 256,

   # init methods (Copied from OLMo 2)
   "init_method": "normal",
   "output_layer_init_method": "normal",
   "init_method_std": 0.02,

   # optimizer settings
   "optimizer": {
     "type": "Adam",
     "params": {
       "lr": 0.00012,
       "betas": [0.9, 0.95],
       "eps": 1.0e-8,
     }
   },

   # for all zero_optimization options, see https://www.deepspeed.ai/docs/config-json/#zero-optimizations-for-fp16-training
  "zero_optimization": {
  "stage": 1,
  "allgather_partitions": true,
  "allgather_bucket_size": 1260000000,
  "overlap_comm": true,
  "reduce_scatter": true,
  "reduce_bucket_size": 1260000000,
  "contiguous_gradients": true,
  "cpu_offload": false
  },
   "min_lr": 0.000012,

   # batch / data settings
   "train_micro_batch_size_per_gpu": 32,
  "gradient_accumulation_steps": 1,
   "data_impl": "mmap",

   # activation checkpointing
   "checkpoint_activations": false,
   "checkpoint_num_layers": 1,
   "partition_activations": false,
   "synchronize_each_layer": false,

   # regularization
   "gradient_clipping": 1.0,
   "weight_decay": 0.1,
   "hidden_dropout": 0,
   "attention_dropout": 0,
   # Flash Attention
   "attention_config": [[["flash"], 22]],
      # "attention_config": [[["flash"], 24]],

   # precision settings
  "precision": "bfloat16",
  "fp32_allreduce": true,
  "bf16": {
    "enabled": true
  },
  "data_types": {
    "grad_accum_dtype": "fp32"
  },

   # misc. training settings
   "train_iters": 500,
   "lr_decay_iters": 500,
   "distributed_backend": "nccl",
   "lr_decay_style": "cosine",
   "warmup": 0.01,
   "checkpoint_factor": 100,
   "eval_interval": 1000,
   "eval_iters": 10,
   "extra_save_iters": [1],

   # logging
   "log_interval": 10,
   "steps_per_print": 10,
   "keep_last_n_checkpoints": 4,
   "wall_clock_breakdown": true,

  "wandb_run_name": "Hubble-1.1B-Baseline-BS-32-No-Activation-Checkpointing",

  
   "memory_profiling": true,
   "memory_profiling_path": "/NS/llm-pretraining/work/afkhan/USC_Colab/gpt-neox/Artifacts/Profiles/Hubble-1.1B-Baseline-BS-32-No-Activation-Checkpointing",
   "profile_step_start": 0,
   "profile_step_stop": 100,

  # Data etc.

  "data_path": "data/enwik8/enwik8_text_document",

  "padded_vocab_size": 50304,

  # or for weighted datasets:
  # "train-data-paths": ["data/enwik8/enwik8_text_document", "data/enwik8/enwik8_text_document"],
  # "test-data-paths": ["data/enwik8/enwik8_text_document", "data/enwik8/enwik8_text_document"],
  # "valid-data-paths": ["data/enwik8/enwik8_text_document", "data/enwik8/enwik8_text_document"],
  # "train-data-weights": [1., 2.],
  # "test-data-weights": [2., 1.],
  # "valid-data-weights": [0.5, 0.4],

  # If weight_by_num_documents is True, Builds dataset weights from a multinomial distribution over groups of data according to the number of documents in each group.
  # WARNING: setting this to True will override any user provided weights
  # "weight_by_num_documents": false,
  # "weighted_sampler_alpha": 0.3,

  # "vocab_file": "data/gpt2-vocab.json",
  # "merge_file": "data/gpt2-merges.txt",

  "vocab_file": "/NS/llm-pretraining/work/afkhan/USC_Colab/gpt-neox/Artifacts/olmo_tokenizer.json",
  "tokenizer_type": "HFTokenizer",
  "save": "checkpoints-Hubble-1.1B-Baseline-BS-32-No-Activation-Checkpointing",
  # "load": "checkpoints",
  "checkpoint_validation_with_forward_pass": False,

  "tensorboard_dir": "tensorboard",
  "log_dir": "logs",
  "use_wandb": True,
  "wandb_host": "https://api.wandb.ai",
  "wandb_project": "hubble-speed-testing",


  "peak_theoretical_tflops": 312,

  "launcher": "slurm",
  "deepspeed_slurm": true,
  "no_ssh_check": true,

  
}
